# Site settings
title: Fictional Memory
email: kirk.shoop@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  an intersection of C++ and Win32
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kirkshoop.github.io" # the base hostname & protocol for your site
twitter_username: kirkshoop
github_username:  kirkshoop

# Build settings
markdown: kramdown

#markdown: redcarpet
#redcarpet:
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap

plantuml:
  plantuml_jar: _bin/plantuml.jar     # path to plantuml jar
  tmp_folder: _plantuml               # tmp folder to put generated image files
  #dot_exe: c:/graphviz/bin/dot.exe    # [optional] path to Graphviz dot execution
  background_color: white             # [optional] UML image background color

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']