# Site settings
title: Fictional Memory
author:
  name: "Kirk Shoop"
  email: kirk.shoop@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  an intersection of C++ and Win32
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kirkshoop.github.io" # the base hostname & protocol for your site
twitter_username: kirkshoop
github_username:  kirkshoop
copyright: "(c) Kirk Shoop, 2010-2022"
encoding: utf-8
timezone: America/San_Francisco

# Build settings
markdown: kramdown

highlighter: rouge

kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

#markdown: redcarpet
#redcarpet:
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]

plugins:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-plantuml
  - jekyll-avatar

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']